In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Задание 1 
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array ([12, 2, 1])
np.linalg.solve (A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [15]:
# Задание 2 
# Перевел уравнения в матрицу. "пустые" значения z во 2 уравнении и y в 4 уравнении взял в матрицу за 0. 
# Получилась невязка 0.7 это большое отклонение? если я допустил ошибку в вычислениях прокоментируйте где именно. Спасибо! 
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array ([1, 7, 12, 7, 15])
np.linalg.lstsq (A, B)

C:\Users\Mitro\AppData\Local\Temp\ipykernel_16880\3455000230.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq (A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [16]:
np.dot (A, [ 1.13919353, -0.90498444, -0.9009803 ])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

In [23]:
def Q(x, y, z):
    return ((np.linalg.norm(np.dot (A, [x, y, z])- B))**2)
Q (1.13919353, -0.90498444, -0.9009803)

0.7152321111819737

In [27]:
# Задание 3 заданная матрица 1 2 3 4 5 6 7 8 9 имеет определитель равный 0. Сделаем расширенную матрицу и проверим ранг.
# ранг расширенной матрицы 3 исходной 2 система не имеет решений. 
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array ([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [86]:
# Задание 3 заданная матрица 1 2 3 4 5 6 7 8 9 имеет определитель равный 0. Внесу изменения в вектор - 1, 1, 1, 
#Сделаем расширенную матрицу и проверим ранг.
# ранг расширенной матрицы 2 исходной 2 система имеет решения. 
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array ([[1, 1, 1]])
C = np.concatenate((A,B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]


(2, 2)

In [85]:
A = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array ([1, 1, 1])
print (np.linalg.solve (A, B))


[-2.5  4.  -1.5]


In [95]:
# Задание № 4 
import scipy 
import scipy.linalg
A = np.array ([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print (P)
print (L)
print (U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [117]:
# Задание № 6
import numpy as np
import matplotlib.pyplot as plt
A = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array ([[2, 5, 11]])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)
print (np.dot(Q, R))
print (np.dot(np.transpose(Q), Q))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -5.55111512e-16 -2.77555756e-16]
 [-5.55111512e-16  1.00000000e+00  5.68989300e-16]
 [-2.77555756e-16  5.68989300e-16  1.00000000e+00]]


In [113]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [126]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1
# Объясните пожалуйста почему выходит ошибка программы? Делал все по видеоуроку. Спасибо! 

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [ ]:
X1 = np.linalg.solve(R1, B1)
X1

In [ ]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)